export const ADD_CRIMINALRECORD = "ADD_CRIMINALRECORD";
export const CHECK_CRIMINALRECORD = "CHECK_CRIMINALRECORD";
export const ADD_IMAGE = "ADD_IMAGE";
export const ADD_RECORD = "ADD_RECORD";
export const CHECK_IDENTITY = "ADD_IDENTITY";
export const ADD_FINGERPRINT = "ADD_FINGERPRINT";
export const CHECK_FORBIDDENTRAVELLER = "CHECK_FORBIDDENTRAVELLER";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
